# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: client.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'client.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x63lient.proto\x12\x0eoxidedb.client\"\x19\n\nGetRequest\x12\x0b\n\x03key\x18\x01 \x01(\x0c\"+\n\x0bGetResponse\x12\r\n\x05value\x18\x01 \x01(\x0c\x12\r\n\x05\x66ound\x18\x02 \x01(\x08\"(\n\nSetRequest\x12\x0b\n\x03key\x18\x01 \x01(\x0c\x12\r\n\x05value\x18\x02 \x01(\x0c\"\x1e\n\x0bSetResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"\x1c\n\rDeleteRequest\x12\x0b\n\x03key\x18\x01 \x01(\x0c\"!\n\x0e\x44\x65leteResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"1\n\x0bScanRequest\x12\x11\n\tstart_key\x18\x01 \x01(\x0c\x12\x0f\n\x07\x65nd_key\x18\x02 \x01(\x0c\"=\n\x0cScanResponse\x12-\n\x07\x65ntries\x18\x01 \x03(\x0b\x32\x1c.oxidedb.client.KeyValuePair\"*\n\x0cKeyValuePair\x12\x0b\n\x03key\x18\x01 \x01(\x0c\x12\r\n\x05value\x18\x02 \x01(\x0c\"\xbb\x01\n\rErrorResponse\x12\x35\n\x04\x63ode\x18\x01 \x01(\x0e\x32\'.oxidedb.client.ErrorResponse.ErrorCode\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x16\n\x0eleader_address\x18\x03 \x01(\t\"J\n\tErrorCode\x12\x06\n\x02OK\x10\x00\x12\x0e\n\nNOT_LEADER\x10\x01\x12\x11\n\rKEY_NOT_FOUND\x10\x02\x12\x12\n\x0eINTERNAL_ERROR\x10\x03\x32\x9b\x02\n\rClientService\x12>\n\x03Get\x12\x1a.oxidedb.client.GetRequest\x1a\x1b.oxidedb.client.GetResponse\x12>\n\x03Set\x12\x1a.oxidedb.client.SetRequest\x1a\x1b.oxidedb.client.SetResponse\x12G\n\x06\x44\x65lete\x12\x1d.oxidedb.client.DeleteRequest\x1a\x1e.oxidedb.client.DeleteResponse\x12\x41\n\x04Scan\x12\x1b.oxidedb.client.ScanRequest\x1a\x1c.oxidedb.client.ScanResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'client_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETREQUEST']._serialized_start=32
  _globals['_GETREQUEST']._serialized_end=57
  _globals['_GETRESPONSE']._serialized_start=59
  _globals['_GETRESPONSE']._serialized_end=102
  _globals['_SETREQUEST']._serialized_start=104
  _globals['_SETREQUEST']._serialized_end=144
  _globals['_SETRESPONSE']._serialized_start=146
  _globals['_SETRESPONSE']._serialized_end=176
  _globals['_DELETEREQUEST']._serialized_start=178
  _globals['_DELETEREQUEST']._serialized_end=206
  _globals['_DELETERESPONSE']._serialized_start=208
  _globals['_DELETERESPONSE']._serialized_end=241
  _globals['_SCANREQUEST']._serialized_start=243
  _globals['_SCANREQUEST']._serialized_end=292
  _globals['_SCANRESPONSE']._serialized_start=294
  _globals['_SCANRESPONSE']._serialized_end=355
  _globals['_KEYVALUEPAIR']._serialized_start=357
  _globals['_KEYVALUEPAIR']._serialized_end=399
  _globals['_ERRORRESPONSE']._serialized_start=402
  _globals['_ERRORRESPONSE']._serialized_end=589
  _globals['_ERRORRESPONSE_ERRORCODE']._serialized_start=515
  _globals['_ERRORRESPONSE_ERRORCODE']._serialized_end=589
  _globals['_CLIENTSERVICE']._serialized_start=592
  _globals['_CLIENTSERVICE']._serialized_end=875
# @@protoc_insertion_point(module_scope)
