# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import client_pb2 as client__pb2

GRPC_GENERATED_VERSION = '1.82.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in client_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ClientServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Get = channel.unary_unary(
                '/oxidedb.client.ClientService/Get',
                request_serializer=client__pb2.GetRequest.SerializeToString,
                response_deserializer=client__pb2.GetResponse.FromString,
                _registered_method=True)
        self.Scan = channel.unary_unary(
                '/oxidedb.client.ClientService/Scan',
                request_serializer=client__pb2.ScanRequest.SerializeToString,
                response_deserializer=client__pb2.ScanResponse.FromString,
                _registered_method=True)
        self.Propose = channel.unary_unary(
                '/oxidedb.client.ClientService/Propose',
                request_serializer=client__pb2.ProposeRequest.SerializeToString,
                response_deserializer=client__pb2.ProposeResponse.FromString,
                _registered_method=True)
        self.GetLock = channel.unary_unary(
                '/oxidedb.client.ClientService/GetLock',
                request_serializer=client__pb2.GetLockRequest.SerializeToString,
                response_deserializer=client__pb2.GetLockResponse.FromString,
                _registered_method=True)
        self.GetWriteRecord = channel.unary_unary(
                '/oxidedb.client.ClientService/GetWriteRecord',
                request_serializer=client__pb2.GetWriteRecordRequest.SerializeToString,
                response_deserializer=client__pb2.GetWriteRecordResponse.FromString,
                _registered_method=True)
        self.FollowerReadIndex = channel.unary_unary(
                '/oxidedb.client.ClientService/FollowerReadIndex',
                request_serializer=client__pb2.FollowerReadIndexRequest.SerializeToString,
                response_deserializer=client__pb2.FollowerReadIndexResponse.FromString,
                _registered_method=True)


class ClientServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def Get(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Scan(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Propose(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLock(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetWriteRecord(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FollowerReadIndex(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ClientServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Get': grpc.unary_unary_rpc_method_handler(
                    servicer.Get,
                    request_deserializer=client__pb2.GetRequest.FromString,
                    response_serializer=client__pb2.GetResponse.SerializeToString,
            ),
            'Scan': grpc.unary_unary_rpc_method_handler(
                    servicer.Scan,
                    request_deserializer=client__pb2.ScanRequest.FromString,
                    response_serializer=client__pb2.ScanResponse.SerializeToString,
            ),
            'Propose': grpc.unary_unary_rpc_method_handler(
                    servicer.Propose,
                    request_deserializer=client__pb2.ProposeRequest.FromString,
                    response_serializer=client__pb2.ProposeResponse.SerializeToString,
            ),
            'GetLock': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLock,
                    request_deserializer=client__pb2.GetLockRequest.FromString,
                    response_serializer=client__pb2.GetLockResponse.SerializeToString,
            ),
            'GetWriteRecord': grpc.unary_unary_rpc_method_handler(
                    servicer.GetWriteRecord,
                    request_deserializer=client__pb2.GetWriteRecordRequest.FromString,
                    response_serializer=client__pb2.GetWriteRecordResponse.SerializeToString,
            ),
            'FollowerReadIndex': grpc.unary_unary_rpc_method_handler(
                    servicer.FollowerReadIndex,
                    request_deserializer=client__pb2.FollowerReadIndexRequest.FromString,
                    response_serializer=client__pb2.FollowerReadIndexResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'oxidedb.client.ClientService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('oxidedb.client.ClientService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ClientService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Get(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/oxidedb.client.ClientService/Get',
            client__pb2.GetRequest.SerializeToString,
            client__pb2.GetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Scan(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/oxidedb.client.ClientService/Scan',
            client__pb2.ScanRequest.SerializeToString,
            client__pb2.ScanResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Propose(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/oxidedb.client.ClientService/Propose',
            client__pb2.ProposeRequest.SerializeToString,
            client__pb2.ProposeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetLock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/oxidedb.client.ClientService/GetLock',
            client__pb2.GetLockRequest.SerializeToString,
            client__pb2.GetLockResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetWriteRecord(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/oxidedb.client.ClientService/GetWriteRecord',
            client__pb2.GetWriteRecordRequest.SerializeToString,
            client__pb2.GetWriteRecordResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FollowerReadIndex(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/oxidedb.client.ClientService/FollowerReadIndex',
            client__pb2.FollowerReadIndexRequest.SerializeToString,
            client__pb2.FollowerReadIndexResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
